Creating arrays



In [1]:
import numpy as np
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)
# np.full(5,2.2)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a= np.array([1,2,3,4,5,6,7])
a[2]


np.int64(3)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,5)

array([3, 4])

In [21]:
np.linspace(1,100,3)

array([  1. ,  50.5, 100. ])

 multidimensional arrays


In [29]:
r,c=3,2
np.zeros((r,c))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
a= np.array([[1 ,2 ,3 ],[4 , 5 ,6 ],[7 ,8 ,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

assign [0,1,2] to last column

In [33]:
a= np.array([[1 ,2 ,3 ],[4 , 5 ,6 ],[7 ,8 ,9]])
a[:,2]=[0,1,2]
a

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

randomly generated arrays

In [37]:
np.random.seed(2)
np.random.rand(4,5)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [40]:
#generating random numbers using normal distribution

np.random.randn(4,4)

array([[-1.86809065,  1.73118467,  1.46767801, -0.33567734],
       [ 0.61134078,  0.04797059, -0.82913529,  0.08771022],
       [ 1.00036589, -0.38109252, -0.37566942, -0.07447076],
       [ 0.43349633,  1.27837923, -0.63467931,  0.50839624]])

In [43]:
#generating random numbers in the matrix 

np.random.seed(2) # to seed the random no generator so that machine generates the no with fixed randomess
np.random.randint(low=0,high=100,size=(5,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

Elementary operations



In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [49]:
a+1


array([1, 2, 3, 4, 5])

comparison 


In [55]:
b =a*2
b


array([0, 2, 4, 6, 8])

In [56]:
a>=b

array([ True, False, False, False, False])

In [63]:
print(b.tolist())

[0, 2, 4, 6, 8]


In [70]:
#printing sum of elements at even index

a=np.arange(0,6)
print(a)
sm=0
for i in range(len(a)):
    if(i>>2 != 1):
        sm+=a[i]



print(sm)

[0 1 2 3 4 5]
6
